# For DNS over HTTPS
#
# Make sure you are using the right image for your arch,
# otherwise you might see 'standard_init_linux.go:190: exec user process caused "exec format error"'

version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:arm
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    
        #  secureoperator:
        #    container_name: secureoperator
        #    image: fardog/secureoperator:latest
        #    restart: unless-stopped
        #    networks:
        #      pihole_net:
        #        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - ServerIP=10.0.0.3
      - DNS1='10.0.0.2#5054'
      - DNS2=''
      - IPv6=false
      - TZ='America/Los_Angeles'
      - DNSMASQ_LISTENING=all 
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
