# For DNS over HTTPS
#
# Make sure you are using the right image for your arch,
# otherwise you might see 'standard_init_linux.go:190: exec user process caused "exec format error"'

version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:arm  # Change to latest for non-arm devices
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    environment:
      - ServerIP=10.0.0.3
      - DNS1='10.0.0.2#5054'
      - DNS2=''
      - IPv6=false
      - TZ='America/Los_Angeles'
      - DNSMASQ_LISTENING=all 
      - "VIRTUAL_HOST=pihole.rpi.lan"
      - "VIRTUAL_PORT=80"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN

  nginx-proxy:  
    #image: jwilder/nginx-proxy           # Use this for amd64 etc.
    image: budry/jwilder-nginx-proxy-arm  # Use this for arm 
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
